versionGroups:
  - label: Use workspace protocol for local packages
    packages: ['**']
    dependencies: ['$LOCAL']
    dependencyTypes: ['!local']
    pinVersion: workspace:*
  - label: Ignore example packages
    packages: ['examples']
    dependencies: ['**']
    isIgnored: true
  - label: Keep type packages in devDependencies
    dependencies: ['@types/**']
    dependencyTypes: ['!dev']
    isBanned: true
  - label: Ban underscore
    packages: ['**']
    dependencies: ['underscore']
    isBanned: true

semverGroups:
  - label: Use exact Node type versions
    dependencies: ['@types/node']
    packages: ['**']
    range: ''
