packages:
  - 'packages/*'
  - 'packages/stores/*'
  - 'docs'
patchedDependencies:
  '@npmcli/run-script': patches/@npmcli__run-script.patch
# https://pnpm.io/settings#cli-settings
engineStrict: true
packageManagerStrictVersion: true
managePackageManagerVersions: false
# https://pnpm.io/settings#build-settings
strictDepBuilds: false
childConcurrency: 10
verifyDepsBeforeRun: warn
# https://pnpm.io/settings#nodejs-settings
useNodeVersion: 26.3.0
# https://pnpm.io/settings#workspace-settings
injectWorkspacePackages: true
disallowWorkspaceCycles: true
# todo: activate after fixing docs and stores versioning
# https://pnpm.io/settings#strictpeerdependencies
# strictPeerDependencies: true

# https://pnpm.io/settings#other-settings
useStderr: true
updateNotifier: true
shellEmulator: true
minimumReleaseAge: 0
